version: 2
jobs:
   build:
     docker:
       - image: circleci/ruby:2.4.1
       - image: circleci/node:6.10
     working_directory: ~/repo
     steps:
       - checkout
       - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
       - run: 
          shell: /bin/sh
          command: npm install
       - run: 
          shell: /bin/sh
          command: './node_modules/.bin/cypress run'
            
            