version: 2.1
orbs:
  cypress: cypress-io/cypress@1.16.1

  jobs:
    run-cy-test:
      working_directory: ~/repo
      steps:
         -checkout
         -run:npm run cy:run
workflows:
  build:
    jobs:
     -run-cy-test/run

