version: 2
jobs:
   build:
     docker:
       - image: circleci/ruby:2.4.1
       - image: circleci/node:6.10
     working_directory: ~/repo
     steps:
       - checkout
       - run: 
          shell: /bin/sh
          command: |
            npm install
            npm run cy:run