version: 2
jobs:
  test:
    docker:
      - image: circleci/<language>:<version TAG>
    steps:
      - checkout
      - run: npm run cy:run
workflows:
  version: 2
  build_test:
    jobs:
      - test

